#!/usr/bin/env node
/**
 * TFS Buyer Lifecycle — n8n Provisioner (Phase 3)
 *
 * For the n8n Cloud instance at N8N_BASE_URL, this:
 *   1. Creates the "GHL Private Integration Token" credential (HTTP Header Auth)
 *   2. Creates the "Notion TFS Integration" credential (Notion API) — only if NOTION_SECRET is set
 *   3. Patches tfs-build/n8n/01_buyer_match_engine.json with a FIELD_IDS lookup
 *      preamble in the "Filter & Match Buyers" code node (reads IDs from
 *      tfs-build/ghl/01_custom_fields_IDS.json generated by provision-ghl.js)
 *   4. Imports + activates all 4 n8n workflows
 *   5. Writes tfs-build/n8n/WORKFLOW_IDS.json with workflow ids, webhook urls, cred ids
 *
 * Idempotent: every step is check-before-create; workflows are updated by name.
 *
 * USAGE (from repo root):
 *   node scripts/provision-n8n.js                # live
 *   DRY_RUN=1 node scripts/provision-n8n.js      # preview (no writes)
 *
 * ENV (from .env):
 *   N8N_BASE_URL       e.g. https://dealpros.app.n8n.cloud
 *   N8N_API_TOKEN      n8n API key  (Settings → API → generate)
 *                      NOTE: the MCP-server JWT is NOT the same thing —
 *                      if auth 401s, generate a proper API key.
 *   GHL_API_TOKEN      proxies into the GHL credential
 *   NOTION_SECRET      optional — skip Notion cred + bridge activation if missing
 *
 * Prereqs: run scripts/provision-ghl.js first so IDs exist for patching.
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ---------- env ----------
function loadEnv() {
  const envPath = path.join(__dirname, '..', '.env');
  if (fs.existsSync(envPath)) {
    for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$/);
      if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
}
loadEnv();

const N8N_BASE = (process.env.N8N_BASE_URL || '').replace(/\/+$/, '');
const N8N_TOKEN = process.env.N8N_API_TOKEN;
const GHL_TOKEN = process.env.GHL_API_TOKEN;
const NOTION_SECRET = process.env.NOTION_SECRET || '';
const DRY_RUN = process.env.DRY_RUN === '1' || process.env.DRY_RUN === 'true';

if (!N8N_BASE || !N8N_TOKEN) {
  console.error('FATAL: N8N_BASE_URL and N8N_API_TOKEN must be set');
  process.exit(1);
}
if (!GHL_TOKEN) {
  console.error('FATAL: GHL_API_TOKEN must be set (used as the GHL credential value)');
  process.exit(1);
}

const HEADERS = {
  'X-N8N-API-KEY': N8N_TOKEN,
  'Accept': 'application/json',
  'Content-Type': 'application/json'
};

// ---------- io ----------
const ROOT = path.join(__dirname, '..');
const read = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const write = (p, obj) => fs.writeFileSync(path.join(ROOT, p), JSON.stringify(obj, null, 2) + '\n');
const exists = (p) => fs.existsSync(path.join(ROOT, p));

// ---------- api ----------
async function api(method, url, body) {
  const fullUrl = url.startsWith('http') ? url : `${N8N_BASE}/api/v1${url}`;
  if (DRY_RUN && method !== 'GET') {
    console.log(`  [DRY] ${method} ${url}`);
    return { __dry: true };
  }
  const res = await fetch(fullUrl, {
    method,
    headers: HEADERS,
    body: body ? JSON.stringify(body) : undefined
  });
  const text = await res.text();
  let json;
  try { json = text ? JSON.parse(text) : {}; } catch { json = { raw: text.slice(0, 500) }; }
  if (!res.ok) {
    const err = new Error(`${method} ${url} → HTTP ${res.status}`);
    err.status = res.status;
    err.body = json;
    throw err;
  }
  return json;
}

// ---------- credentials ----------
async function listCredentials() {
  try {
    const r = await api('GET', '/credentials');
    return r.data || r.credentials || r || [];
  } catch (e) {
    if (e.status === 405 || e.status === 404) {
      // n8n Cloud public API may not expose LIST for credentials — fall back
      console.log('  (credentials LIST not supported — will attempt upsert via name lookup in workflows)');
      return [];
    }
    throw e;
  }
}

async function ensureCredential(name, type, data) {
  console.log(`\n[cred] "${name}" (type=${type})`);
  const all = await listCredentials();
  const existing = all.find(c => c.name === name && c.type === type);
  if (existing) {
    console.log(`  ✓ exists id=${existing.id}`);
    return existing.id;
  }
  try {
    const created = await api('POST', '/credentials', { name, type, data });
    const id = created.id || (created.data && created.data.id);
    console.log(`  + created id=${id || '(dry)'}`);
    return id;
  } catch (e) {
    console.log(`  ✗ FAILED ${e.status}: ${JSON.stringify(e.body).slice(0, 240)}`);
    throw e;
  }
}

// ---------- match engine field-id patch ----------
function patchMatchEngine(fieldIdsObj) {
  // Build a lookup from human name → GHL field id
  const idByName = {};
  for (const f of fieldIdsObj.fields) {
    if (f.id) idByName[f.name] = f.id;
  }

  const engine = read('tfs-build/n8n/01_buyer_match_engine.json');
  const matchNode = engine.nodes.find(n => n.name === 'Filter & Match Buyers');
  if (!matchNode) throw new Error('match engine JSON missing "Filter & Match Buyers" node');

  const preamble =
    `// --- PATCHED by provision-n8n.js (${new Date().toISOString()}) ---\n` +
    `// Prefer ID-based lookup; fall back to name match.\n` +
    `const FIELD_IDS = ${JSON.stringify(idByName, null, 2)};\n` +
    `const getFieldById = (buyer, nameKey) => {\n` +
    `  const id = FIELD_IDS[nameKey];\n` +
    `  if (!id) return null;\n` +
    `  const m = (buyer.customFields || []).find(f => f.id === id);\n` +
    `  return m ? m.value : null;\n` +
    `};\n`;

  const originalJs = matchNode.parameters.jsCode;
  // Remove any previous PATCH block, then prepend fresh one.
  const cleaned = originalJs.replace(/^\/\/ --- PATCHED by provision-n8n\.js[\s\S]*?^};\s*\n/m, '');

  // Rewrite the inner getField() to prefer ID lookup with name fallback.
  const rewritten = cleaned.replace(
    /const getField = \(name\) => \{[\s\S]*?\};/,
    `const getField = (name) => {\n    const byId = getFieldById(buyer, name);\n    if (byId !== null && byId !== undefined) return byId;\n    const match = (buyer.customFields || []).find(f => f.name === name || f.fieldKey === name);\n    return match ? match.value : null;\n  };`
  );

  matchNode.parameters.jsCode = preamble + '\n' + rewritten;
  write('tfs-build/n8n/01_buyer_match_engine.json', engine);
  console.log(`\n[patch] match engine JSON patched with ${Object.keys(idByName).length} field ID lookups`);
}

// ---------- workflow upsert ----------
function scrubWorkflow(wf, credentials) {
  const clone = JSON.parse(JSON.stringify(wf));
  delete clone.id;
  delete clone.versionId;
  delete clone.createdAt;
  delete clone.updatedAt;
  delete clone.tags;
  delete clone.active;
  delete clone.triggerCount;
  delete clone.staticData;
  delete clone.pinData;
  delete clone.meta;
  clone.settings = clone.settings || { executionOrder: 'v1', timezone: 'America/Phoenix' };

  // Attach real credential ids by name
  for (const node of clone.nodes || []) {
    if (!node.credentials) continue;
    for (const credType of Object.keys(node.credentials)) {
      const ref = node.credentials[credType];
      const credName = ref && ref.name;
      if (!credName) continue;
      const realId = credentials[credName];
      if (realId) {
        node.credentials[credType] = { id: realId, name: credName };
      }
    }
  }
  return clone;
}

async function upsertWorkflow(filepath, credentials) {
  const wfJson = read(filepath);
  const name = wfJson.name;
  console.log(`\n[wf] ${name}  (${filepath})`);

  // Check if exists by name
  let existing = null;
  try {
    const list = await api('GET', '/workflows');
    const all = list.data || list.workflows || list || [];
    existing = all.find(w => w.name === name);
  } catch (e) {
    console.log(`  (list error ${e.status}; attempting create)`);
  }

  const payload = scrubWorkflow(wfJson, credentials);

  let workflow;
  if (existing) {
    console.log(`  ↺ updating existing id=${existing.id}`);
    workflow = await api('PUT', `/workflows/${existing.id}`, payload);
    workflow.id = existing.id;
  } else {
    workflow = await api('POST', '/workflows', payload);
  }
  const id = workflow.id || workflow.data && workflow.data.id;
  console.log(`  ✓ id=${id || '(dry)'}`);

  // Activate
  if (!DRY_RUN && id) {
    try {
      await api('POST', `/workflows/${id}/activate`);
      console.log(`  ✓ activated`);
    } catch (e) {
      console.log(`  ! activate failed ${e.status}: ${JSON.stringify(e.body).slice(0, 200)}`);
    }
  }

  // Extract webhook paths
  const webhooks = (wfJson.nodes || [])
    .filter(n => n.type === 'n8n-nodes-base.webhook')
    .map(n => ({
      name: n.name,
      path: n.parameters && n.parameters.path,
      url: `${N8N_BASE}/webhook/${n.parameters && n.parameters.path}`
    }));

  return { name, id, file: filepath, webhooks };
}

// ---------- main ----------
(async () => {
  console.log(`===== n8n Provisioner =====`);
  console.log(`Base:    ${N8N_BASE}`);
  console.log(`Dry run: ${DRY_RUN ? 'YES' : 'no'}`);
  console.log(`Notion:  ${NOTION_SECRET ? 'secret set — will create cred + activate bridge' : 'MISSING — Notion bridge will be skipped'}`);

  // Preflight: hit /workflows to verify auth
  try {
    await api('GET', '/workflows?limit=1');
    console.log('  ✓ n8n auth OK');
  } catch (e) {
    console.error(`\nFATAL: n8n auth failed (${e.status}). Body: ${JSON.stringify(e.body).slice(0, 300)}`);
    console.error(`If you pasted the MCP-server JWT, that won't work — generate a real API key:`);
    console.error(`  n8n → Settings → API → Create API Key`);
    process.exit(1);
  }

  // Load GHL field IDs (requires provision-ghl.js to have run)
  if (!exists('tfs-build/ghl/01_custom_fields_IDS.json')) {
    console.error(`\nFATAL: tfs-build/ghl/01_custom_fields_IDS.json not found.`);
    console.error(`Run scripts/provision-ghl.js first.`);
    process.exit(1);
  }
  const fieldIds = read('tfs-build/ghl/01_custom_fields_IDS.json');

  // 1. Patch the match engine JSON
  patchMatchEngine(fieldIds);

  // 2. Credentials
  const credentials = {};
  credentials['GHL Private Integration Token'] = await ensureCredential(
    'GHL Private Integration Token',
    'httpHeaderAuth',
    { name: 'Authorization', value: `Bearer ${GHL_TOKEN}` }
  );
  if (NOTION_SECRET) {
    credentials['Notion TFS Integration'] = await ensureCredential(
      'Notion TFS Integration',
      'notionApi',
      { apiKey: NOTION_SECRET }
    );
  }

  // 3. Workflows
  const workflowFiles = [
    'tfs-build/n8n/01_buyer_match_engine.json',
    'tfs-build/n8n/03_helper_increment.json'
  ];
  if (NOTION_SECRET) workflowFiles.push('tfs-build/n8n/02_notion_bridge.json');
  else console.log('\n(skipping Notion bridge import — NOTION_SECRET not set)');

  const results = [];
  for (const f of workflowFiles) {
    try {
      results.push(await upsertWorkflow(f, credentials));
    } catch (e) {
      console.log(`  ✗ FAILED: ${e.message}`);
      if (e.body) console.log(`    body: ${JSON.stringify(e.body).slice(0, 300)}`);
      results.push({ file: f, error: e.message });
    }
  }

  const out = {
    generated_at: new Date().toISOString(),
    n8n_base: N8N_BASE,
    credentials,
    workflows: results,
    next_steps: [
      'Confirm the webhook URL(s) below return HTTP 200 via curl.',
      'Set n8n env vars in your n8n Cloud instance: Settings → Variables (Cloud) or env in config:',
      '  GHL_LOCATION_ID = ' + (process.env.GHL_LOCATION_ID || '(set in .env)'),
      NOTION_SECRET ? '  NOTION_DEAL_INVENTORY_DB_ID = ' + (process.env.NOTION_DEAL_INVENTORY_DB_ID || '(unset)') : '  NOTION_DEAL_INVENTORY_DB_ID = — skipped (no Notion secret)',
      '  TZ = America/Phoenix'
    ]
  };
  write('tfs-build/n8n/WORKFLOW_IDS.json', out);

  console.log(`\n[5/5] Summary`);
  for (const r of results) {
    console.log(`  ${r.error ? '✗' : '✓'} ${r.name || r.file}  id=${r.id || '—'}`);
    for (const w of r.webhooks || []) console.log(`      webhook: ${w.url}`);
  }
  console.log(`\n  wrote tfs-build/n8n/WORKFLOW_IDS.json`);

  const anyFailed = results.some(r => r.error);
  if (anyFailed) process.exit(2);

  console.log(`\n✓ Phase 3 (n8n) complete. Commit tfs-build/n8n/WORKFLOW_IDS.json + patched match engine JSON.`);
})().catch(e => {
  console.error('\nFATAL:', e.message);
  if (e.body) console.error('body:', JSON.stringify(e.body).slice(0, 500));
  process.exit(1);
});
